# Generated by Django 3.1.7 on 2022-04-30 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image1', models.ImageField(upload_to='producto', verbose_name='Imagen 1')),
                ('image2', models.ImageField(upload_to='producto', verbose_name='Imagen 2')),
                ('image3', models.ImageField(upload_to='producto', verbose_name='Imagen 3')),
                ('image4', models.ImageField(upload_to='producto', verbose_name='Imagen 4')),
                ('status', models.BooleanField(default=True, help_text='Alta/Baja', verbose_name='Estado')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.business', verbose_name='Empresa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('id',),
            },
        ),
    ]
