# Generated by Django 3.1.7 on 2022-04-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Negocio')),
                ('direction', models.CharField(max_length=50, verbose_name='Dirección')),
                ('ruc', models.IntegerField(blank=True, verbose_name='RUC')),
                ('history', models.TextField(blank=True, verbose_name='Historia')),
                ('vision', models.TextField(verbose_name='visión')),
                ('mision', models.TextField(verbose_name='mision')),
                ('image', models.ImageField(upload_to='empresa', verbose_name='imagen')),
                ('status', models.BooleanField(default=True, help_text='Alta/Baja', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
    ]
